version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app           #
    environment:
      - PYTHONPATH=/app

#
#  frontend:
#    build: ./frontend
#    container_name: frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./frontend:/app
#    env_file:
#      - .env
#    depends_on:
#      - backend
